Added a LWS recipe with FullCalendar
trailheadapps/lwc-recipes pull request #609
Opened 2021-12-21 09:58 UTC by pozil

This PR introduces a new recipe for Lightning Web Security (LWS) with the FullCalendar library. This library wasn't supported by Locker and now works with LWS

## With Locker

![lwc-recipes-without-lws](https://user-images.githubusercontent.com/5071767/146910248-636eaaf7-da1f-4222-977f-64fad22ea900.png)

## With LWS

![lwc-recipes-with-lws](https://user-images.githubusercontent.com/5071767/146910293-fee92534-c8b9-46aa-b436-6d5ed32483dc.png)

2021-12-23 05:45 UTC, satyasekharcvb requested changes
You might have to include `libsFullCalendar` to X3rd_Party_Libs.flexipage-meta.xml

2021-12-23 08:47 UTC, pozil commented
Good catch, thanks @satyasekharcvb.
It's fixed.

2021-12-23 08:52 UTC, satyasekharcvb approved these changes

2021-12-24 11:56 UTC, pozil commented
@albarivas we can merge this PR when the blog post is ready.

2022-01-19 12:26 UTC, albarivas approved these changes

2022-01-19 13:17 UTC, merged