chore(record-picker): add some comments
trailheadapps/lwc-recipes pull request #867
Opened 2023-10-25 09:16 UTC by arosenbach

### What does this PR do?
Chore: adding more comments to the code to give some explanation.

### What issues does this PR fix or reference?

#<Insert GitHub Issue>

## The PR fulfills these requirements:

[x] Tests for the proposed changes have been added/updated.
[x] Code linting and formatting was performed.

2023-10-25 22:21 UTC, econstantin requested changes

2023-10-25 22:21 UTC, econstantin commented on force-app/main/default/lwc/recordPickerDynamicTarget/recordPickerDynamicTarget.js
> +// As of today, `lightning-record-picker` supports a single targets.
nit: only supports a single target

2023-10-25 22:21 UTC, econstantin commented
looks good, just a minor comment.  consider approved from my end after addressing.

2023-11-06 07:42 UTC, pozil approved these changes
LGTM, thanks for the update.

2023-11-06 07:44 UTC, merged