Lightning record picker multi value
trailheadapps/lwc-recipes pull request #893
Opened 2024-01-10 13:50 UTC by arosenbach

### What does this PR do?

New sample component to showcase `lightning-record-picker`: multi-value record picker

![image](https://github.com/trailheadapps/lwc-recipes/assets/12657050/cff9db64-e987-411a-a455-ac6480f3c470)

### What issues does this PR fix or reference?

#892

## The PR fulfills these requirements:

[x] Tests for the proposed changes have been added/updated.
[x] Code linting and formatting was performed.

2024-01-10 14:15 UTC, RamiNoufal approved these changes

2024-01-10 14:15 UTC, RamiNoufal commented on force-app/main/default/lwc/recordPickerMultiValue/recordPickerMultiValue.js
> +        this._clearRecordPickerSeliction();
typo: _clearRecordPickerSelection

2024-01-10 14:15 UTC, RamiNoufal commented on force-app/main/default/lwc/recordPickerMultiValue/recordPickerMultiValue.html
> +            Type a search terms and select records.
type: terms -> term

2024-01-12 09:09 UTC, pozil requested changes
Great work team. Thanks for the contribution.
Can you fix the bit that I suggested?

2024-01-12 09:21 UTC, pozil approved these changes

2024-01-12 09:21 UTC, pozil commented
Great work. Merging now.

2024-01-12 09:24 UTC, merged